- name: Print Variables
  hosts: all
  vars:
    Url: play.example.com
    Project: ansible
 # vars_files:
  #  - exaple-vars.yml
  vars_prompt:
    - name: Url
      prompt: enter Url
      private: no
  tasks:
    - name: Print Url
      debug:
        msg: Url = {{ Url }}
    - name: print url from task
      debug:
        msg: Url = {{ Url }}
      vars:
        Url: google.example.com

# Print Date
- name: Demo on dynamic vars
  hosts: all
  tasks:
    - name: Gather date
      shell: date +%F
      register: out
    - name: print date
      debug:
        msg: date={{ out.stdout }}


- name: print some facts
  hosts: all
  tasks:
    - name: print facts
      debug:
        msg: Hostname={{ ansible_hostname }}