- name: Print Variables
  hosts: all
  vars:
    Url: play.example.com
    Project: ansible
  tasks:
    - name: Print Url
      debug:
        msg: Url = {{ Url }}
    - name: print url from task
      debug:
        msg: Url = {{ Url }}
      var:
        Url: google.example.com