- name: Import nodejs common role
  include_role:
    name: common
    tasks_from: nodejs

- name: Import nexus common role
  include_role:
    name: common
    tasks_from: node_exporter

- name: Import nexus common role
  include_role:
    name: common
    tasks_from: filebeat
  vars:
    IS_STRUCTURED: true
    LOG_FILES:
      - { file: "/var/log/{{COMPONENT}}.log", type: "{{COMPONENT}}" }