- name: install nginx
  apt:
    name: nginx
    update_cache: yes
    state: present

- name: install npm
  apt:
    name: npm
    state: present

- name: Download Component
  get_url:
    url: http://3.239.241.106:8081/repository/frontend/frontend-{{ APP_VERSION }}.zip
    dest: /tmp/frontend.zip
    username: admin
    password: admin123
    force_basic_auth: yes

- name: Remove default content
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/www/html
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default

- name: Create HtDocs directory
  file:
    path: /var/www/html
    state: directory

- name: Create HtDocs directory
  file:
    path: /var/www/html/frontend
    state: directory

- name: Unzip downloaded content
  unarchive:
    src: /tmp/frontend.zip
    dest: /var/www/html/frontend
    remote_src: yes

- name: Move File foo to destination bar
  command: mv /var/www/html/frontend/todo.conf /etc/nginx/sites-enabled

- name: Start service
  systemd:
    name: nginx
    state: restarted
    enabled: yes
