- name: Import java common role
  include_role:
    name: common
    tasks_from: java

- name: Import nexus common role
  include_role:
    name: common
    tasks_from: node_exporter

- name: Import nexus common role
  include_role:
    name: common
    tasks_from: filebeat