- name: Import java common role
  include_role:
    name: common
    tasks_from: java

- name: Import nexus common role
  include_role:
    name: common
    tasks_from: node_exporter

- name: Import filebeat common role
  include_role:
    name: common
    tasks_from: filebeat
  vars:
    IS_STRUCTURED: false
    IS_JAVA: true
    LOG_FILES:
      - { file: "/var/log/{{COMPONENT}}.log", type: "{{COMPONENT}}" }