- name: Install java-8
  apt:
    name: openjdk-8-jdk-headless
    update_cache: yes
    state: present

- name: Install maven
  apt:
    name: maven
    state: present

- name: Download Component
  get_url:
    url: http://34.201.35.232:8081/repository/users/users-{{ APP_VERSION }}.zip
    dest: /tmp/frontend.zip
    username: admin
    password: admin123