- name: Install java-8
  apt:
    name: openjdk-8-jdk-headless
    update_cache: yes
    state: present

- name: Download arftifacts from nexus
  include_tasks: download-nexus-artifacts.yml

- name: Download arftifacts from nexus
  include_tasks: unarchive.yml

- name: Download arftifacts from nexus
  include_tasks: setup-systemD.yml