- name: Setup hostname
  shell: set-hostname {{COMPONENT}}

- name: Update Rsyslog config
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/todo.conf

- name: Update Filebeat Configuration
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted